{{- if .Values.client.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "headscale.fullname" . }}-client-job
  labels:
    {{- include "headscale.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "headscale.fullname" . }}-client-job
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets"]
  verbs: ["get", "list", "watch", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "headscale.fullname" . }}-client-job
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "headscale.fullname" . }}-client-job
subjects:
- kind: ServiceAccount
  name: {{ include "headscale.fullname" . }}-client-job
  namespace: {{ .Release.Namespace }}
{{- end }}
