{{- if and .Values.client.enabled (not .Values.server.enabled) .Values.client.authKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headscale.fullname" . }}-client-authkey
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  authkey: {{ .Values.client.authKey | quote }}
{{- end }}
