{{- if .Values.client.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "headscale.fullname" . }}-create-client-secret
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 10
  activeDeadlineSeconds: 600
  template:
    spec:
      serviceAccountName: {{ include "headscale.fullname" . }}-client-job
      restartPolicy: OnFailure
      volumes:
      - name: job-script
        configMap:
          name: {{ include "headscale.fullname" . }}-client-job-script
          defaultMode: 0755
      containers:
      - name: create-secret
        image: "{{ .Values.client.job.image.repository }}:{{ .Values.client.job.image.tag }}"
        imagePullPolicy: {{ .Values.client.job.image.pullPolicy }}
        command: ["/scripts/ensure-client-key.sh"]
        volumeMounts:
        - name: job-script
          mountPath: /scripts
          readOnly: true
{{- end }}
