apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "headscale.serviceAccountName" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "headscale.fullname" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmap"]
  verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "headscale.fullname" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "headscale.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "headscale.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
