{{- if and .Values.ui.enabled (.Values.ui.podDisruptionBudget.enabled | default false) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "headscale.fullname" . }}-ui
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  selector:
    matchLabels:
      {{- include "headscale.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  {{- $pdb := .Values.ui.podDisruptionBudget }}
  {{- if hasKey $pdb "minAvailable" }}
  minAvailable: {{ $pdb.minAvailable }}
  {{- else if hasKey $pdb "maxUnavailable" }}
  maxUnavailable: {{ $pdb.maxUnavailable }}
  {{- else }}
  maxUnavailable: 1
  {{- end }}
{{- end }}
